image: debian/stable
packages:
  - build-essential
  - cmake
  - ninja-build
  - pkg-config
  - ncurses-dev
  - libreadline-dev
  - libedit-dev
  - libgoogle-perftools-dev
  - libgmp-dev
  - libssl-dev
  - unixodbc-dev
  - zlib1g-dev
  - libarchive-dev
  - libossp-uuid-dev
  - libxext-dev
  - libice-dev
  - libjpeg-dev
  - libxinerama-dev
  - libxft-dev
  - libxpm-dev
  - libxt-dev
  - libdb-dev
  - libpcre2-dev
  - libyaml-dev
  - zip
  - git
  - emacs
secrets:
  - 750079bb-9735-473b-bebf-db897c9f0c6b
  - 72d5c3dc-f83f-4cc2-96e3-b2b08f6ee8a0
sources:
  - git@git.sr.ht:~eshel/sweep
tasks:
  - getswipl: |
      git clone --recursive https://github.com/SWI-Prolog/swipl-devel.git
      cd swipl-devel
      mkdir build
      cd build
      export LANG="en_US.UTF-8"
      sudo localectl set-locale LANG=en_US.UTF-8
      localectl set-locale LANG=en_US.UTF-8
      cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DSWIPL_INSTALL_IN_LIB=ON -DSWIPL_PACKAGES_ODBC=OFF -DSWIPL_PACKAGES_JAVA=OFF -DSWIPL_PACKAGES_X=OFF -DINSTALL_DOCUMENTATION=OFF -G Ninja ..
      ninja
      sudo ninja install
  - build: |
      cd sweep
      export LD_LIBRARY_PATH=/usr/local/lib
      make
      make sweep.info
      make check
