image: debian/stable
packages:
  - build-essential
  - cmake
  - ninja-build
  - pkg-config
  - ncurses-dev
  - libreadline-dev
  - libedit-dev
  - libgoogle-perftools-dev
  - libgmp-dev
  - libssl-dev
  - unixodbc-dev
  - zlib1g-dev
  - libarchive-dev
  - libossp-uuid-dev
  - libxext-dev
  - libice-dev
  - libjpeg-dev
  - libxinerama-dev
  - libxft-dev
  - libxpm-dev
  - libxt-dev
  - libdb-dev
  - libpcre2-dev
  - libyaml-dev
  - zip
  - git
secrets:
  - 750079bb-9735-473b-bebf-db897c9f0c6b
  - 72d5c3dc-f83f-4cc2-96e3-b2b08f6ee8a0
sources:
  - git@git.sr.ht:~eshel/sweep
tasks:
  - build: |
      cd sweep
      make
      make info
